### ISSUE TITLE
define dggs-zonequery:parameters:dist

### ISSUE THREAD

**Issue by rggibb** [opengeospatial/ogcapi-discrete-global-grid-systems#10]
![image](https://user-images.githubusercontent.com/7731644/121996002-fa044000-cdfb-11eb-8403-4407a2f2e786.png)

**Comment by allixender** [comment]
Alex: claiming

**Comment by allixender** [comment]
```yaml
dist:
      name: dist
      in: query
      required: false
      schema:
        type: array
        minItems: 1
        maxItems: 2
        items:
          type: string
```
